-- What was the first item & last item from the menu purchased by each customer?

WITH FIRST_LAST_ITEM AS
(
    SELECT S.CUSTOMER_ID,M.PRODUCT_ID,M.PRODUCT_NAME,S.ORDER_DATE,
    row_number()OVER(PARTITION BY S.CUSTOMER_ID ORDER BY S.ORDER_DATE) AS RN,
    row_number()OVER(PARTITION BY S.CUSTOMER_ID ORDER BY S.ORDER_DATE DESC) AS RN1 
    FROM {{ source('danny_raw', 'SALES') }} S
    JOIN {{ source('danny_raw', 'MENU') }} M
    ON S.PRODUCT_ID = M.PRODUCT_ID
)
SELECT CUSTOMER_ID,
    max(CASE WHEN RN = 1 THEN PRODUCT_NAME END) AS FIRST_PRODUCT,
    max(CASE WHEN RN = 1 THEN ORDER_DATE END) AS FIRST_ORDER_DATE,
    max(CASE WHEN RN1 = 1 THEN PRODUCT_NAME END) AS LAST_ORDER,
    max(CASE WHEN RN1 = 1 THEN ORDER_DATE END) AS LAST_ORDER_DATE
FROM FIRST_LAST_ITEM
GROUP BY CUSTOMER_ID