WITH POPULAR_ITEM AS
(
    SELECT S.CUSTOMER_ID,M.PRODUCT_NAME,
    COUNT(M.PRODUCT_ID) AS TOT_PRODUCT,
    DENSE_RANK()OVER(PARTITION BY S.CUSTOMER_ID ORDER BY COUNT(M.PRODUCT_ID) DESC) AS RNK
    FROM SALES S
    JOIN MENU M
    ON S.PRODUCT_ID = M.PRODUCT_ID
    GROUP BY 1,2
)
SELECT CUSTOMER_ID,PRODUCT_NAME,TOT_PRODUCT 
FROM POPULAR_ITEM
WHERE RNK = 1