-- What is the total items and amount spent for each member before they became a member?

SELECT S.CUSTOMER_ID,COUNT(S.PRODUCT_ID) AS PROD_COUNTS,
SUM(PRICE) AS TOT_SPENT
FROM SALES S
JOIN MEMBERS MEM
ON S.CUSTOMER_ID = MEM.CUSTOMER_ID
JOIN MENU M
ON M.PRODUCT_ID = S.PRODUCT_ID
WHERE S.ORDER_DATE < MEM.JOIN_DATE
GROUP BY 1
