sources:
  - name: raw
    database: DB
    schema: DEMO_SCH
    tables:
      - name: Customers
      - name: Products
      - name: Orders

  - name: danny_raw
    database: DANNY_DB
    schema: DANNY_SCHEMA
    tables:
      - name: MEMBERS
      - name: MENU
      - name: SALES

      
        